_wandb:
    value:
        cli_version: 0.21.3
        e:
            mqduqudjlwdstce0xxnwzz30oavyimon:
                codePath: training/train_yolo.py
                codePathLocal: training/train_yolo.py
                cpu_count: 16
                cpu_count_logical: 16
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "61285326848"
                        used: "27543719936"
                email: jswleetaiwan@gmail.com
                executable: /home/exouser/cv-training/venv/bin/python3
                git:
                    commit: 375951447e682b58f5254212fdd70253ed2c4078
                    remote: git@github.com:jswlee/cv-training.git
                gpu: GRID A100X-20C
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "21474836480"
                      name: GRID A100X-20C
                      uuid: GPU-831c7a5f-8cd1-11f0-b7ec-ee25c8b4f4fc
                host: cv-training
                memory:
                    total: "63190446080"
                os: Linux-6.14.0-29-generic-x86_64-with-glibc2.39
                program: /home/exouser/cv-training/training/train_yolo.py
                python: CPython 3.11.13
                root: /home/exouser/cv-training
                startedAt: "2025-09-08T17:03:32.656877Z"
                writerId: mqduqudjlwdstce0xxnwzz30oavyimon
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.13
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
batch_size:
    value: 4
device:
    value: cuda
epochs:
    value: 30
image_size:
    value: 1920
model:
    value: yolov8n.pt
