_wandb:
    value:
        cli_version: 0.21.3
        e:
            2ph7i3iby8gbrxmnxri76x1hq4x8lh2c:
                codePath: training/train_yolo.py
                codePathLocal: training/train_yolo.py
                email: jswleetaiwan@gmail.com
                executable: /usr/local/bin/python3
                git:
                    commit: fdc3a4184577d5d0127498733f3981080606183d
                    remote: https://github.com/jswlee/cv-training.git
                host: MacBookPro.lan
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/jlee/Desktop/github/cv-training/training/train_yolo.py
                python: CPython 3.12.0
                root: /Users/jlee/Desktop/github/cv-training
                startedAt: "2025-09-08T19:41:33.725880Z"
                writerId: 2ph7i3iby8gbrxmnxri76x1hq4x8lh2c
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.0
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
batch_size:
    value: 2
dataset:
    value: data/roi_masked_data/data.yaml
device:
    value: mps
epochs:
    value: 30
image_size:
    value: 1920
model:
    value: yolov8n.pt
